### ISSUE TITLE
no module name bs4

### ISSUE THREAD

**Issue by dhrubo11** [Jeyaprabu/Unacademy-Downloader#1]
when i try to run the script on my windows 10 pc . it say following error 

C:\>unac_down_main.py
Traceback (most recent call last):
  File "C:\Unac_down_main.py", line 7, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

**Comment by Jeyaprabu** [comment]
Hi,
You need to install BeautifulSoup package
use pip to install
refer [ https://stackoverflow.com/questions/33331850/importerror-no-module-named-bs4-in-windows ](url)

**Comment by dhrubo11** [comment]
C:\Users\dhrub\Desktop\Unacademy-Downloader-master>Unac_down_main.py
Traceback (most recent call last):
  File "C:\Users\dhrub\Desktop\Unacademy-Downloader-master\Unac_down_main.py", line 9, in <module>
    import requests
ImportError: No module named requests
